version: '3.9'

services:
  backend:
    build:
      context: ./backend
    container_name: mini_bi_backend
    env_file:
      - ./backend/.env.example
    volumes:
      - ./backend/data:/app/data
    network_mode: host

  frontend:
    build:
      context: ./frontend
    container_name: mini_bi_frontend
    network_mode: host
    depends_on:
      - backend
